name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Zip the application
      run: zip -r deploy.zip . -x '*.git*'

    - name: Upload to S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  # Substitua pela região correta
      run: |
        aws s3 cp deploy.zip s3://bucket-eb/deploy.zip  # Substitua pelo nome correto do bucket

    - name: Deploy to Elastic Beanstalk
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-east-1'  # Substitua pela região correta
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "nodeteste" \
          --version-label $GITHUB_SHA \
          --source-bundle S3Bucket="bucket-eb",S3Key="deploy.zip"
        aws elasticbeanstalk update-environment \
          --application-name "nodeteste" \
          --environment-name "nodeteste-env" \
          --version-label $GITHUB_SHA
